databases:
  - name: myrailssite71
    databaseName: myrailssite71
    user: myrailssite

services:
  - type: web
    name: myrailssite71
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    preDeployCommand: "bundle exec rails db:migrate"
    autoDeploy: false
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: myrailssite71
          property: connectionString
      - key: SECRET_KEY_BASE
        generateValue: true